# Generated by Django 4.0.3 on 2022-03-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0002_remove_menu_price_remove_menu_tariff1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ctg_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=156, unique=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('character', models.TextField()),
            ],
        ),
    ]
