# Generated by Django 4.0.3 on 2022-03-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0006_contact_footer_header_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
