# Generated by Django 4.0.3 on 2022-03-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0007_contact_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.AddField(
            model_name='contact',
            name='about_site',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
