# Generated by Django 4.0.3 on 2022-03-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0009_contact_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='about_site_ru',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='about_site_uz',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='city_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='city_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='working_time_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='working_time_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ctg_about',
            name='character_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ctg_about',
            name='character_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ctg_about',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ctg_about',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='character_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='character_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='character_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='character_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tariffs',
            name='character_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tariffs',
            name='character_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tariffs',
            name='name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tariffs',
            name='name_uz',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tariffs',
            name='type_price_ru',
            field=models.CharField(max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='tariffs',
            name='type_price_uz',
            field=models.CharField(max_length=156, null=True),
        ),
    ]
