# Generated by Django 4.0.3 on 2022-03-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0010_contact_about_site_ru_contact_about_site_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_header', models.CharField(max_length=255, verbose_name='name_header')),
                ('name_header_ru', models.CharField(max_length=255, null=True, verbose_name='name_header')),
                ('name_header_uz', models.CharField(max_length=255, null=True, verbose_name='name_header')),
                ('about_header', models.TextField(verbose_name='about_header')),
                ('about_header_ru', models.TextField(null=True, verbose_name='about_header')),
                ('about_header_uz', models.TextField(null=True, verbose_name='about_header')),
                ('image_header', models.ImageField(upload_to='', verbose_name='image_header')),
                ('name_footer', models.CharField(max_length=255, verbose_name='name_footer')),
                ('name_footer_ru', models.CharField(max_length=255, null=True, verbose_name='name_footer')),
                ('name_footer_uz', models.CharField(max_length=255, null=True, verbose_name='name_footer')),
                ('about_footer', models.TextField(verbose_name='about_footer')),
                ('about_footer_ru', models.TextField(null=True, verbose_name='about_footer')),
                ('about_footer_uz', models.TextField(null=True, verbose_name='about_footer')),
                ('image_footer', models.ImageField(upload_to='', verbose_name='image_footer')),
            ],
        ),
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_services', models.CharField(max_length=255, verbose_name='name_services')),
                ('name_services_ru', models.CharField(max_length=255, null=True, verbose_name='name_services')),
                ('name_services_uz', models.CharField(max_length=255, null=True, verbose_name='name_services')),
                ('about_services', models.TextField(verbose_name='about_services')),
                ('about_services_ru', models.TextField(null=True, verbose_name='about_services')),
                ('about_services_uz', models.TextField(null=True, verbose_name='about_services')),
                ('name_nurses', models.CharField(max_length=255, verbose_name='name_nurses')),
                ('name_nurses_ru', models.CharField(max_length=255, null=True, verbose_name='name_nurses')),
                ('name_nurses_uz', models.CharField(max_length=255, null=True, verbose_name='name_nurses')),
                ('about_nurses', models.CharField(max_length=400, verbose_name='about_nurses')),
                ('about_nurses_ru', models.CharField(max_length=400, null=True, verbose_name='about_nurses')),
                ('about_nurses_uz', models.CharField(max_length=400, null=True, verbose_name='about_nurses')),
                ('name_search', models.CharField(max_length=255, verbose_name='name_search')),
                ('name_search_ru', models.CharField(max_length=255, null=True, verbose_name='name_search')),
                ('name_search_uz', models.CharField(max_length=255, null=True, verbose_name='name_search')),
                ('about_search', models.CharField(max_length=400, verbose_name='about_search')),
                ('about_search_ru', models.CharField(max_length=400, null=True, verbose_name='about_search')),
                ('about_search_uz', models.CharField(max_length=400, null=True, verbose_name='about_search')),
                ('name_choose', models.CharField(max_length=255, verbose_name='name_choose')),
                ('name_choose_ru', models.CharField(max_length=255, null=True, verbose_name='name_choose')),
                ('name_choose_uz', models.CharField(max_length=255, null=True, verbose_name='name_choose')),
                ('choose_us', models.TextField(verbose_name='choose_us')),
                ('choose_us_ru', models.TextField(null=True, verbose_name='choose_us')),
                ('choose_us_uz', models.TextField(null=True, verbose_name='choose_us')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_time', models.CharField(max_length=255, verbose_name='working_time')),
                ('working_time_ru', models.CharField(max_length=255, null=True, verbose_name='working_time')),
                ('working_time_uz', models.CharField(max_length=255, null=True, verbose_name='working_time')),
                ('city', models.CharField(max_length=255, null=True, verbose_name='city')),
                ('city_ru', models.CharField(max_length=255, null=True, verbose_name='city')),
                ('city_uz', models.CharField(max_length=255, null=True, verbose_name='city')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('address_ru', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('address_uz', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('phone_number', models.CharField(max_length=100, verbose_name='phone_number')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('emergency_number', models.CharField(max_length=100, verbose_name='emergency_number')),
                ('about_site', models.CharField(max_length=400, null=True, verbose_name='about_site')),
                ('about_site_ru', models.CharField(max_length=400, null=True, verbose_name='about_site')),
                ('about_site_uz', models.CharField(max_length=400, null=True, verbose_name='about_site')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('character', models.TextField(verbose_name='character')),
                ('character_ru', models.TextField(null=True, verbose_name='character')),
                ('character_uz', models.TextField(null=True, verbose_name='character')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
            ],
        ),
        migrations.DeleteModel(
            name='Ctg_about',
        ),
        migrations.DeleteModel(
            name='Header',
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.AlterField(
            model_name='contact',
            name='about_site',
            field=models.CharField(max_length=400, null=True, verbose_name='about_site'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='about_site_ru',
            field=models.CharField(max_length=400, null=True, verbose_name='about_site'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='about_site_uz',
            field=models.CharField(max_length=400, null=True, verbose_name='about_site'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=255, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='emergency_number',
            field=models.CharField(max_length=100, verbose_name='emergency_number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='working_time',
            field=models.CharField(max_length=255, verbose_name='working_time'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='working_time_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='working_time'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='working_time_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='working_time'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='number',
            field=models.CharField(max_length=255, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='character',
            field=models.TextField(verbose_name='character'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='character_ru',
            field=models.TextField(null=True, verbose_name='character'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='character_uz',
            field=models.TextField(null=True, verbose_name='character'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(blank=True, max_length=156, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='age',
            field=models.IntegerField(verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='number',
            field=models.CharField(max_length=255, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='services',
            name='slug',
            field=models.SlugField(blank=True, max_length=156, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='character',
            field=models.TextField(verbose_name='character'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='character_ru',
            field=models.TextField(null=True, verbose_name='character'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='character_uz',
            field=models.TextField(null=True, verbose_name='character'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='name_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='name_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='price',
            field=models.IntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='slug',
            field=models.SlugField(blank=True, max_length=156, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='type_price',
            field=models.CharField(max_length=156, verbose_name='type_price'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='type_price_ru',
            field=models.CharField(max_length=156, null=True, verbose_name='type_price'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='type_price_uz',
            field=models.CharField(max_length=156, null=True, verbose_name='type_price'),
        ),
        migrations.AlterField(
            model_name='users',
            name='map',
            field=models.TextField(max_length=255, verbose_name='map'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.CharField(max_length=255, verbose_name='number'),
        ),
    ]
